### ISSUE TITLE
React 15.0 support

### ISSUE THREAD

**Issue by jVerhaert** [sergiodxa/react-simple-modal#7]
Please update the dependency of react to 15.0 
Currently can't update project to new react version.

Thanks in advance!

**Comment by jVerhaert** [comment]
created pull request
https://github.com/sergiodxa/react-simple-modal/pull/8

**Comment by sergiodxa** [comment]
I just published the `v1.1.5` to [npm](https://www.npmjs.com/package/react-simple-modal) with your PR, thanks!
